import { BankId, BankConfig, PreviewGroove } from '../types';
import {
  getNeurofunkPattern,
  getJungleAmenPattern,
  getJumpUpPattern,
  getLiquidSunsetPattern,
  getDarkstepPattern,
  getMinimalRollerPattern,
  getHalftimePattern,
  getSambaDnbPattern,
  getUkDrillstepPattern,
  getDubJunglePattern,
  getMainframeNeuroPattern,
  getFestivalVipPattern,
} from './presetPatterns';

export const PRESET_GROOVES: PreviewGroove[] = [
  { id: 'g1', name: 'NEUROFUNK', genre: 'DNB', bpm: 175, bank: 'A', color: '#00F0FF', pattern: getNeurofunkPattern() },
  { id: 'g2', name: 'JUNGLE AMEN', genre: 'DNB', bpm: 172, bank: 'B', color: '#00FF66', pattern: getJungleAmenPattern() },
  { id: 'g3', name: 'JUMP UP', genre: 'DNB', bpm: 175, bank: 'C', color: '#FFD60A', pattern: getJumpUpPattern() },
  { id: 'g4', name: 'LIQUID SUNSET', genre: 'DNB', bpm: 174, bank: 'D', color: '#BF5AF2', pattern: getLiquidSunsetPattern() },
  { id: 'g5', name: 'DARKSTEP', genre: 'DNB', bpm: 178, bank: 'A', color: '#FF375F', pattern: getDarkstepPattern() },
  { id: 'g6', name: 'MINIMAL ROLLER', genre: 'DNB', bpm: 174, bank: 'C', color: '#FF9F0A', pattern: getMinimalRollerPattern() },
  { id: 'g7', name: 'HALFTIME', genre: 'DNB', bpm: 174, bank: 'B', color: '#0A84FF', pattern: getHalftimePattern() },
  { id: 'g8', name: 'SAMBA DNB', genre: 'DNB', bpm: 174, bank: 'D', color: '#FF2D55', pattern: getSambaDnbPattern() },
  { id: 'g9', name: 'DRILLSTEP', genre: 'DNB', bpm: 173, bank: 'A', color: '#30D158', pattern: getUkDrillstepPattern() },
  { id: 'g10', name: 'DUB JUNGLE', genre: 'DNB', bpm: 170, bank: 'B', color: '#34C759', pattern: getDubJunglePattern() },
  { id: 'g11', name: 'MAINFRAME', genre: 'DNB', bpm: 176, bank: 'A', color: '#64D2FF', pattern: getMainframeNeuroPattern() },
  { id: 'g12', name: 'FESTIVAL VIP', genre: 'DNB', bpm: 175, bank: 'C', color: '#FF007F', pattern: getFestivalVipPattern() },
];

export const BANKS: Record<BankId, BankConfig> = {
  A: {
    id: 'A',
    name: 'NEUROFUNK & TECHSTEP',
    subtitle: 'Heavy reese bass, punchy kicks & tech stabs',
    color: '#00F0FF',
    pads: [
      { id: 0, name: 'PUNCH KICK', category: 'kick', keyShortcut: '1', color: '#00F0FF', description: 'Punchy 175Hz DNB kick' },
      { id: 1, name: 'REESE BASS', category: 'sub', keyShortcut: '2', color: '#0071e3', description: 'Detuned neuro reese' },
      { id: 2, name: 'CRACK SNARE', category: 'snare', keyShortcut: '3', color: '#5ac8fa', description: 'High pitched 200Hz crack' },
      { id: 3, name: 'AMEN GHOST', category: 'clap', keyShortcut: '4', color: '#0071e3', description: 'Ghost breakbeat snare' },
      { id: 4, name: 'RIDE BELL', category: 'percussion', keyShortcut: 'Q', color: '#64d2ff', description: 'Fast ride bell' },
      { id: 5, name: 'TIGHT HAT', category: 'hihat', keyShortcut: 'W', color: '#ffd60a', description: 'Crisp closed hat' },
      { id: 6, name: 'OPEN SHUFFLE', category: 'hihat', keyShortcut: 'E', color: '#ffd60a', description: 'Shuffle open hat' },
      { id: 7, name: 'SHAKER LOOP', category: 'percussion', keyShortcut: 'R', color: '#ff9f0a', description: 'Fast 16th shaker' },
      { id: 8, name: 'DIRTY BASS 1', category: 'sub', keyShortcut: 'A', color: '#30d158', description: 'Distorted mid bass' },
      { id: 9, name: 'DIRTY BASS 2', category: 'sub', keyShortcut: 'S', color: '#30d158', description: 'High pitched FM growl' },
      { id: 10, name: 'TECH STAB', category: 'synth', keyShortcut: 'D', color: '#64d2ff', description: 'Dark minor chord stab' },
      { id: 11, name: 'ATMOSPHERE', category: 'fx', keyShortcut: 'F', color: '#64d2ff', description: 'Eerie pad chord' },
      { id: 12, name: 'LAZER ZAP', category: 'fx', keyShortcut: 'Z', color: '#bf5af2', description: 'Sci-fi laser drop' },
      { id: 13, name: 'REVERSE CYM', category: 'percussion', keyShortcut: 'X', color: '#bf5af2', description: 'Reverse crash buildup' },
      { id: 14, name: 'MC SHOUT', category: 'vocal', keyShortcut: 'C', color: '#5e5ce6', description: 'MC vocal shout' },
      { id: 15, name: 'IMPACT', category: 'fx', keyShortcut: 'V', color: '#0a84ff', description: 'Huge reverb drop' },
    ],
  },
  B: {
    id: 'B',
    name: 'JUNGLE & AMEN BREAKS',
    subtitle: 'Fast amen chops, deep 808 sub & dub sirens',
    color: '#00FF66',
    pads: [
      { id: 0, name: 'HEAVY KICK', category: 'kick', keyShortcut: '1', color: '#00FF66', description: 'Deep jungle kick' },
      { id: 1, name: 'SUB 808 BASS', category: 'sub', keyShortcut: '2', color: '#34c759', description: 'Deep 40Hz sub tone' },
      { id: 2, name: 'FAT SNARE', category: 'snare', keyShortcut: '3', color: '#ff9f0a', description: 'Classic jungle snare' },
      { id: 3, name: 'GHOST CLAP', category: 'clap', keyShortcut: '4', color: '#ff2d55', description: 'Ghost chop snare' },
      { id: 4, name: 'WOBBLE BASS', category: 'synth', keyShortcut: 'Q', color: '#bf5af2', description: 'Sub wobble bass' },
      { id: 5, name: 'TRAP HAT', category: 'hihat', keyShortcut: 'W', color: '#ffd60a', description: 'Crisp jungle hat' },
      { id: 6, name: 'OPEN HAT', category: 'hihat', keyShortcut: 'E', color: '#ffd60a', description: 'Sizzling open cymbal' },
      { id: 7, name: 'GROWL BASS', category: 'synth', keyShortcut: 'R', color: '#ff9f0a', description: 'Mid bass growl' },
      { id: 8, name: 'SCREECH', category: 'synth', keyShortcut: 'A', color: '#30d158', description: 'Rave screech lead' },
      { id: 9, name: 'METAL HIT', category: 'percussion', keyShortcut: 'S', color: '#30d158', description: 'Metallic break hit' },
      { id: 10, name: 'BRASS HIT', category: 'synth', keyShortcut: 'D', color: '#64d2ff', description: 'Dub reggae brass stab' },
      { id: 11, name: 'GUNSHOT', category: 'fx', keyShortcut: 'F', color: '#64d2ff', description: 'Gunshot FX' },
      { id: 12, name: 'VOX PRE-DROP', category: 'vocal', keyShortcut: 'Z', color: '#bf5af2', description: '"OH MY GOD!" shout' },
      { id: 13, name: 'RISER', category: 'fx', keyShortcut: 'X', color: '#bf5af2', description: 'White noise riser' },
      { id: 14, name: 'DOWNLIFTER', category: 'fx', keyShortcut: 'C', color: '#ff375f', description: 'Noise drop sweep' },
      { id: 15, name: 'DUB SIREN', category: 'fx', keyShortcut: 'V', color: '#ff9f0a', description: 'Roots dub sound siren' },
    ],
  },
  C: {
    id: 'C',
    name: 'JUMP UP & ROLLERS',
    subtitle: 'Foghorn bass, bouncy 2-step & rave stabs',
    color: '#FFD60A',
    pads: [
      { id: 0, name: 'BOUNCY KICK', category: 'kick', keyShortcut: '1', color: '#FFD60A', description: 'Punchy 2-step kick' },
      { id: 1, name: 'FOGHORN BASS', category: 'sub', keyShortcut: '2', color: '#ff9f0a', description: 'Screeching jump up horn' },
      { id: 2, name: 'CRACK SNARE', category: 'snare', keyShortcut: '3', color: '#ff375f', description: 'Snappy high snare' },
      { id: 3, name: 'CLAP', category: 'clap', keyShortcut: '4', color: '#ff2d55', description: 'Layered tight clap' },
      { id: 4, name: 'ROLLER SUB', category: 'sub', keyShortcut: 'Q', color: '#34c759', description: 'Deep rolling sine sub' },
      { id: 5, name: 'CLOSED HAT', category: 'hihat', keyShortcut: 'W', color: '#ffd60a', description: 'Short tight hat' },
      { id: 6, name: 'OPEN HAT', category: 'hihat', keyShortcut: 'E', color: '#ffd60a', description: 'Offbeat splash hat' },
      { id: 7, name: 'WOBBLE BASS', category: 'synth', keyShortcut: 'R', color: '#bf5af2', description: 'Bouncy wobble LFO' },
      { id: 8, name: 'LASER DROP', category: 'fx', keyShortcut: 'A', color: '#64d2ff', description: 'Pitch dive laser' },
      { id: 9, name: 'SQUEAK BASS', category: 'synth', keyShortcut: 'S', color: '#ff375f', description: 'High pitched squeak' },
      { id: 10, name: 'RAVE STAB', category: 'synth', keyShortcut: 'D', color: '#64d2ff', description: 'Classic 90s rave chord' },
      { id: 11, name: 'ATMOSPHERE', category: 'fx', keyShortcut: 'F', color: '#bf5af2', description: 'Eerie string swell' },
      { id: 12, name: 'RIDE BELL', category: 'percussion', keyShortcut: 'Z', color: '#32ade6', description: 'Swung ride cymbal' },
      { id: 13, name: 'WOOD RIM', category: 'percussion', keyShortcut: 'X', color: '#30d158', description: 'Wood rimshot' },
      { id: 14, name: 'MC VOCAL', category: 'vocal', keyShortcut: 'C', color: '#ff9f0a', description: '"LET THE BASS DROP!"' },
      { id: 15, name: 'SPINBACK', category: 'fx', keyShortcut: 'V', color: '#00F0FF', description: 'DJ deck spinback' },
    ],
  },
  D: {
    id: 'D',
    name: 'LIQUID & ATMOSPHERE',
    subtitle: 'Warm sub-bass, soulful rhodes chords & silky hats',
    color: '#BF5AF2',
    pads: [
      { id: 0, name: 'WARM KICK', category: 'kick', keyShortcut: '1', color: '#BF5AF2', description: 'Warm organic kick' },
      { id: 1, name: 'WARM DEEP SUB', category: 'sub', keyShortcut: '2', color: '#af52de', description: 'Pure 50Hz warm sub' },
      { id: 2, name: 'LIQUID SNARE', category: 'snare', keyShortcut: '3', color: '#da8fff', description: 'Crisp bright snare' },
      { id: 3, name: 'RIMSHOT', category: 'clap', keyShortcut: '4', color: '#af52de', description: 'Smooth acoustic rim' },
      { id: 4, name: 'RHODES CHORD', category: 'synth', keyShortcut: 'Q', color: '#64d2ff', description: 'Lush minor 9th Rhodes' },
      { id: 5, name: 'SILKY HAT', category: 'hihat', keyShortcut: 'W', color: '#ffd60a', description: 'Soft silky hi-hat' },
      { id: 6, name: 'OPEN HAT', category: 'hihat', keyShortcut: 'E', color: '#ffd60a', description: 'Brushed open hat' },
      { id: 7, name: 'SHAKER 16TH', category: 'percussion', keyShortcut: 'R', color: '#30d158', description: 'Latin rolling shaker' },
      { id: 8, name: 'VOCAL CHOP', category: 'vocal', keyShortcut: 'A', color: '#ff9f0a', description: 'Warm soulful vocal chop' },
      { id: 9, name: 'LIQUID LEAD', category: 'synth', keyShortcut: 'S', color: '#ff375f', description: 'Sweet flute lead' },
      { id: 10, name: 'BRUSH CRASH', category: 'percussion', keyShortcut: 'D', color: '#64d2ff', description: 'Soft jazz brush crash' },
      { id: 11, name: 'PAD CHORD', category: 'synth', keyShortcut: 'F', color: '#bf5af2', description: 'Warm ambient pad' },
      { id: 12, name: 'SUB GLIDE', category: 'sub', keyShortcut: 'Z', color: '#af52de', description: 'Portamento 808 sub' },
      { id: 13, name: 'CHIME FX', category: 'fx', keyShortcut: 'X', color: '#32ade6', description: 'Crystal sparkle chimes' },
      { id: 14, name: 'REVERSE FX', category: 'fx', keyShortcut: 'C', color: '#30d158', description: 'Reverse cymbal swell' },
      { id: 15, name: 'DOWNLIFTER', category: 'fx', keyShortcut: 'V', color: '#ffd60a', description: 'Warm air downlifter' },
    ],
  },
};
