import { BankId, BankConfig, PreviewGroove } from '../types';
import {
  getMaddixBigRoomPattern,
  getBrejchaJokerPattern,
  getArtbatProgressivePattern,
  getNoisiaNeurofunkPattern,
  getMaddixAcidPattern,
  getBrejchaHighTechPattern,
  getKorolovaMelodicPattern,
  getSubFocusJumpUpPattern,
  getMaddixReverseBassPattern,
  getBrejchaSpaceDubPattern,
  getArtbatBrassHymnPattern,
  getChaseStatusJunglePattern,
  getKazantipAnthemPattern,
  getDavidGuettaFutureRavePattern,
  getHardTechnoWarehousePattern,
} from './presetPatterns';

export const PRESET_GROOVES: PreviewGroove[] = [
  { id: 'g1', name: 'MADDIX • BIG ROOM RAVE', genre: 'MADDIX', bpm: 140, bank: 'A', color: '#00F0FF', pattern: getMaddixBigRoomPattern() },
  { id: 'g2', name: 'BREJCHA • JOKER ROLLER', genre: 'BREJCHA', bpm: 127, bank: 'B', color: '#FF9F0A', pattern: getBrejchaJokerPattern() },
  { id: 'g3', name: 'ARTBAT • HORIZON PROGRESSIVE', genre: 'ARTBAT', bpm: 125, bank: 'C', color: '#BF5AF2', pattern: getArtbatProgressivePattern() },
  { id: 'g4', name: 'NOISIA • NEUROFUNK DROP', genre: 'DNB', bpm: 175, bank: 'D', color: '#30D158', pattern: getNoisiaNeurofunkPattern() },
  { id: 'g5', name: 'KAZANTIP • ORANGE ANTHEM 303', genre: 'KAZANTIP', bpm: 142, bank: 'E', color: '#39FF14', pattern: getKazantipAnthemPattern() },
  { id: 'g6', name: 'DAVID GUETTA • FUTURE RAVE', genre: 'FUTURE RAVE', bpm: 128, bank: 'F', color: '#00F0FF', pattern: getDavidGuettaFutureRavePattern() },
  { id: 'g7', name: 'GARD TECHNO • INDUSTRIAL 152', genre: 'HARD TECHNO', bpm: 152, bank: 'G', color: '#FF2D55', pattern: getHardTechnoWarehousePattern() },
  { id: 'g8', name: 'MADDIX • ACID TECHNO DROP', genre: 'MADDIX', bpm: 144, bank: 'A', color: '#39FF14', pattern: getMaddixAcidPattern() },
  { id: 'g9', name: 'BREJCHA • HIGH-TECH MINIMAL', genre: 'BREJCHA', bpm: 128, bank: 'B', color: '#FFD60A', pattern: getBrejchaHighTechPattern() },
  { id: 'g10', name: 'KOROLOVA • MELODIC VOYAGE', genre: 'KOROLOVA', bpm: 124, bank: 'C', color: '#64D2FF', pattern: getKorolovaMelodicPattern() },
  { id: 'g11', name: 'SUB FOCUS • JUMP UP ROLLER', genre: 'DNB', bpm: 174, bank: 'D', color: '#FF375F', pattern: getSubFocusJumpUpPattern() },
  { id: 'g12', name: 'CHASE & STATUS • AMEN BREAK', genre: 'DNB', bpm: 175, bank: 'D', color: '#30D158', pattern: getChaseStatusJunglePattern() },
];

export const BANKS: Record<BankId, BankConfig> = {
  A: {
    id: 'A',
    name: 'MADDIX • BIG ROOM & RAVE',
    artist: 'MADDIX & HARDWELL',
    subtitle: 'Overdriven rumble kicks, screaming 303 acid & 7-voice supersaws',
    color: '#00F0FF',
    defaultBpm: 140,
    pads: [
      { id: 0, name: 'MADDIX RUMBLE', category: 'kick', keyShortcut: '1', color: '#00F0FF', description: 'Overdriven 909 sub rumble kick' },
      { id: 1, name: 'ACID 303 MADDIX', category: 'sub', keyShortcut: '2', color: '#39FF14', description: 'Resonant TB-303 screaming overdrive' },
      { id: 2, name: 'BIG ROOM CLAP', category: 'clap', keyShortcut: '3', color: '#5ac8fa', description: 'Massive stereo stadium clap' },
      { id: 3, name: 'REVERSE BASS', category: 'sub', keyShortcut: '4', color: '#ff9f0a', description: 'Hard techno offbeat reverse punch' },
      { id: 4, name: 'HYPNOTIC SUPERSAW', category: 'synth', keyShortcut: 'Q', color: '#ff375f', description: '7-voice detuned massive rave lead' },
      { id: 5, name: '909 DRIVING HAT', category: 'hihat', keyShortcut: 'W', color: '#ffd60a', description: 'Crisp relentless 909 closed hat' },
      { id: 6, name: 'SIZZLE OPEN HAT', category: 'hihat', keyShortcut: 'E', color: '#ffd60a', description: 'Driving sizzling 909 open hat' },
      { id: 7, name: 'SUB ROLLER 42HZ', category: 'sub', keyShortcut: 'R', color: '#30d158', description: 'Distorted 42Hz sub rumble drone' },
      { id: 8, name: 'HARDSTYLE SCREECH', category: 'synth', keyShortcut: 'A', color: '#ff2d55', description: 'Harsh abrasive filter scream' },
      { id: 9, name: 'ANVIL DROP', category: 'percussion', keyShortcut: 'S', color: '#32ade6', description: 'High metal warehouse percussion' },
      { id: 10, name: 'DARK TECH STAB', category: 'synth', keyShortcut: 'D', color: '#bf5af2', description: 'Detuned stadium minor chord' },
      { id: 11, name: 'MADDIX LASER', category: 'fx', keyShortcut: 'F', color: '#64d2ff', description: 'Punchy high attack laser transient' },
      { id: 12, name: 'SUB BOMB 808', category: 'sub', keyShortcut: 'Z', color: '#0071e3', description: 'Massive pitch-diving sub bomb' },
      { id: 13, name: 'NOISE RISER', category: 'fx', keyShortcut: 'X', color: '#bf5af2', description: 'Heavy white noise tension build' },
      { id: 14, name: 'MADDIX VOX', category: 'vocal', keyShortcut: 'C', color: '#ff9f0a', description: '"TODAY IS THE DAY / ACID"' },
      { id: 15, name: 'STADIUM REVERB BOMB', category: 'fx', keyShortcut: 'V', color: '#ff375f', description: 'Warehouse sub explosion drop' },
    ],
  },
  B: {
    id: 'B',
    name: 'BORIS BREJCHA • HIGH-TECH MINIMAL',
    artist: 'BORIS BREJCHA',
    subtitle: 'Clicky sub kicks, bouncy Joker bass, duck percs & pluck arps',
    color: '#FF9F0A',
    defaultBpm: 127,
    pads: [
      { id: 0, name: 'BREJCHA CLICK KICK', category: 'kick', keyShortcut: '1', color: '#FF9F0A', description: 'High transient click + deep sub kick' },
      { id: 1, name: 'JOKER ROLLING BASS', category: 'sub', keyShortcut: '2', color: '#30d158', description: 'Bouncy square-saw 16th rolling bass' },
      { id: 2, name: 'WOOD RIMSHOT', category: 'snare', keyShortcut: '3', color: '#5ac8fa', description: 'Snappy organic wooden rimshot' },
      { id: 3, name: 'DUCK QUACK CLIK', category: 'percussion', keyShortcut: '4', color: '#ffd60a', description: 'Boris Brejcha signature pitch perc' },
      { id: 4, name: 'MINIMAL PLUCK ARP', category: 'synth', keyShortcut: 'Q', color: '#64d2ff', description: 'Plucked analog filter lead' },
      { id: 5, name: 'CRISP MICRO HAT', category: 'hihat', keyShortcut: 'W', color: '#ffd60a', description: 'Ultra-tight micro closed hat' },
      { id: 6, name: 'SWUNG OPEN HAT', category: 'hihat', keyShortcut: 'E', color: '#ffd60a', description: 'Bouncy swung offbeat open hat' },
      { id: 7, name: 'MODULATED SUB', category: 'sub', keyShortcut: 'R', color: '#0071e3', description: 'Deep modulated minimal sub-bass' },
      { id: 8, name: 'TECHNO BLEEP', category: 'percussion', keyShortcut: 'A', color: '#ff375f', description: 'High-pitched resonant synth blip' },
      { id: 9, name: 'HIGH WOOD PERC', category: 'percussion', keyShortcut: 'S', color: '#32ade6', description: 'Sharp resonant wood click' },
      { id: 10, name: 'BREJCHA CHORD', category: 'synth', keyShortcut: 'D', color: '#bf5af2', description: 'Atmospheric space-delayed minor chord' },
      { id: 11, name: 'GLITCH NOISE FX', category: 'fx', keyShortcut: 'F', color: '#30d158', description: 'Micro glitch reverse texture' },
      { id: 12, name: 'SUB DIVE 126', category: 'sub', keyShortcut: 'Z', color: '#5e5ce6', description: 'Sub sine click dive' },
      { id: 13, name: 'FILTERED RISER', category: 'fx', keyShortcut: 'X', color: '#ff9f0a', description: 'Resonant highpass noise sweep' },
      { id: 14, name: 'GLITCH VOCAL CHOP', category: 'vocal', keyShortcut: 'C', color: '#ff375f', description: 'Boris-style stuttered vocal chop' },
      { id: 15, name: 'ACOUSTIC PULSE', category: 'fx', keyShortcut: 'V', color: '#FF9F0A', description: 'Subtle minimal room acoustic pulse' },
    ],
  },
  C: {
    id: 'C',
    name: 'ARTBAT & KOROLOVA • MELODIC TECHNO',
    artist: 'ARTBAT & KOROLOVA',
    subtitle: 'Rolling progressive saw bass, analog brass stabs & lush reverb plucks',
    color: '#BF5AF2',
    defaultBpm: 125,
    pads: [
      { id: 0, name: 'PROGRESSIVE KICK', category: 'kick', keyShortcut: '1', color: '#BF5AF2', description: 'Warm deep 909 kick with rich low end' },
      { id: 1, name: 'MELODIC SAW BASS', category: 'sub', keyShortcut: '2', color: '#0071e3', description: 'Rolling multi-saw progressive bassline' },
      { id: 2, name: 'STEREO TECH CLAP', category: 'clap', keyShortcut: '3', color: '#5ac8fa', description: 'Lush wide stereo reverb clap' },
      { id: 3, name: 'ANALOG TOM PERC', category: 'percussion', keyShortcut: '4', color: '#30d158', description: 'Warm resonant analog low tom' },
      { id: 4, name: 'ARTBAT BRASS STAB', category: 'synth', keyShortcut: 'Q', color: '#ff375f', description: 'Signature detuned analog brass chord' },
      { id: 5, name: 'SILKY CLOSED HAT', category: 'hihat', keyShortcut: 'W', color: '#ffd60a', description: 'Soft smooth 16th closed hat' },
      { id: 6, name: 'WIDE OPEN CYM', category: 'hihat', keyShortcut: 'E', color: '#ffd60a', description: 'Silky open hat with gentle stereo tail' },
      { id: 7, name: 'KOROLOVA WARM PAD', category: 'synth', keyShortcut: 'R', color: '#64d2ff', description: 'Lush minor 9th atmospheric pad chord' },
      { id: 8, name: 'REVERB PLUCK', category: 'synth', keyShortcut: 'A', color: '#34c759', description: 'Cinematic melodic pluck lead' },
      { id: 9, name: 'SHAKER 16TH', category: 'percussion', keyShortcut: 'S', color: '#64d2ff', description: 'Silky 16th progressive shaker' },
      { id: 10, name: 'EUPHORIC LEAD', category: 'synth', keyShortcut: 'D', color: '#ff9f0a', description: 'Singing analog saw lead' },
      { id: 11, name: 'ATMOSPHERE DRONE', category: 'fx', keyShortcut: 'F', color: '#32ade6', description: 'Deep hypnotic space reverb drone' },
      { id: 12, name: 'SUB SINE WARMTH', category: 'sub', keyShortcut: 'Z', color: '#0071e3', description: 'Pure 45Hz sub roller' },
      { id: 13, name: 'DOWNLIFTER SWEEP', category: 'fx', keyShortcut: 'X', color: '#bf5af2', description: 'Atmospheric white noise downlifter' },
      { id: 14, name: 'SOULFUL ECHO VOX', category: 'vocal', keyShortcut: 'C', color: '#ff375f', description: 'Spacious emotive vocal phrase snippet' },
      { id: 15, name: 'SPACE IMPACT', category: 'fx', keyShortcut: 'V', color: '#BF5AF2', description: 'Deep cinematic low-end boom' },
    ],
  },
  D: {
    id: 'D',
    name: 'DRUM & BASS • NOISIA & SUB FOCUS',
    artist: 'NOISIA & SUB FOCUS',
    subtitle: 'Punchy 180Hz kicks, tearout reese basses, 200Hz crack snares & foghorns',
    color: '#30D158',
    defaultBpm: 175,
    pads: [
      { id: 0, name: 'PUNCH DNB KICK', category: 'kick', keyShortcut: '1', color: '#30D158', description: '180Hz transient punch kick' },
      { id: 1, name: 'TEAROUT REESE BASS', category: 'sub', keyShortcut: '2', color: '#ff9f0a', description: 'Distorted multi-saw neuro reese' },
      { id: 2, name: '200HZ CRACK SNARE', category: 'snare', keyShortcut: '3', color: '#ff375f', description: 'Piercing transient 200Hz snare crack' },
      { id: 3, name: 'AMEN GHOST CHOP', category: 'snare', keyShortcut: '4', color: '#ff2d55', description: 'Fast breakbeat ghost chop snare' },
      { id: 4, name: 'NASTY FOGHORN', category: 'synth', keyShortcut: 'Q', color: '#ffd60a', description: 'Piercing heavy jump-up foghorn' },
      { id: 5, name: 'ROLLING 16TH HAT', category: 'hihat', keyShortcut: 'W', color: '#ffd60a', description: 'Relentless 16th rolling closed hat' },
      { id: 6, name: 'RIDE CYMBAL BELL', category: 'hihat', keyShortcut: 'E', color: '#64d2ff', description: 'Crisp syncopated ride bell' },
      { id: 7, name: 'SUB SINE 45HZ', category: 'sub', keyShortcut: 'R', color: '#0071e3', description: 'Deep vibrating 45Hz sub roller' },
      { id: 8, name: 'NEURO GROWL FM', category: 'synth', keyShortcut: 'A', color: '#34c759', description: 'Aggressive FM modulated mid bass' },
      { id: 9, name: 'DUB SIREN ROOTS', category: 'fx', keyShortcut: 'S', color: '#ff9f0a', description: 'Authentic Dub/Jungle sound system siren' },
      { id: 10, name: 'RAVE CHORD 90S', category: 'synth', keyShortcut: 'D', color: '#64d2ff', description: 'Euphoric rave piano / stab' },
      { id: 11, name: 'AMEN BREAK ROLL', category: 'percussion', keyShortcut: 'F', color: '#ff2d55', description: 'Classic chopped jungle break roll' },
      { id: 12, name: '808 SUB SLIDE', category: 'sub', keyShortcut: 'Z', color: '#5e5ce6', description: 'Deep portamento sub dive' },
      { id: 13, name: 'REVERSE CRASH FX', category: 'fx', keyShortcut: 'X', color: '#32ade6', description: 'Tension cymbal riser' },
      { id: 14, name: 'MC PRE-DROP SHOUT', category: 'vocal', keyShortcut: 'C', color: '#ffd60a', description: '"LET THE BASS DROP!"' },
      { id: 15, name: 'DJ SPINBACK FX', category: 'fx', keyShortcut: 'V', color: '#30D158', description: 'Vinyl deck reverse spinback' },
    ],
  },
  E: {
    id: 'E',
    name: 'ACID 303 • KAZANTIP ANTHEM',
    artist: 'TB-303 & KAZANTIP',
    subtitle: 'Legendary Kazantip orange festival anthems, squelching 303 acid lines & rave stabs',
    color: '#39FF14',
    defaultBpm: 142,
    pads: [
      { id: 0, name: '909 ACID KICK', category: 'kick', keyShortcut: '1', color: '#39FF14', description: 'Classic 909 acid rave kick with sub tail' },
      { id: 1, name: 'TB-303 SQUELCH', category: 'sub', keyShortcut: '2', color: '#00F0FF', description: 'Screaming 303 resonant diode squelch' },
      { id: 2, name: 'RAVE CLAP 90S', category: 'clap', keyShortcut: '3', color: '#ff9f0a', description: 'Snappy Kazantip beach stadium clap' },
      { id: 3, name: 'ACID REVERSE', category: 'sub', keyShortcut: '4', color: '#ff375f', description: 'Punchy 142 BPM reverse sub bass' },
      { id: 4, name: 'KAZANTIP LEAD', category: 'synth', keyShortcut: 'Q', color: '#ffd60a', description: 'Iconic Kazantip anthem glide lead' },
      { id: 5, name: '909 TIGHT HAT', category: 'hihat', keyShortcut: 'W', color: '#ffd60a', description: 'Crisp relentless 909 closed hat' },
      { id: 6, name: 'KAZANTIP OPEN', category: 'hihat', keyShortcut: 'E', color: '#64d2ff', description: 'Offbeat sizzling 909 open hat' },
      { id: 7, name: 'ACID DRONE 303', category: 'sub', keyShortcut: 'R', color: '#30d158', description: 'Low resonant 303 drone bass' },
      { id: 8, name: 'RESONANT SLIDE', category: 'synth', keyShortcut: 'A', color: '#39FF14', description: 'High-Q 303 filter envelope glide' },
      { id: 9, name: 'RAVE PIANO STAB', category: 'synth', keyShortcut: 'S', color: '#00F0FF', description: '90s Kazantip rave piano chord' },
      { id: 10, name: 'KAZANTIP CHORD', category: 'synth', keyShortcut: 'D', color: '#bf5af2', description: 'Sunset festival atmospheric minor chord' },
      { id: 11, name: 'ACID FILTER SWEEP', category: 'fx', keyShortcut: 'F', color: '#ff375f', description: 'Resonant TB-303 highpass noise sweep' },
      { id: 12, name: 'SUB DROP BOOM', category: 'sub', keyShortcut: 'Z', color: '#0071e3', description: 'Sub bass dive explosion' },
      { id: 13, name: 'ORANGE RISER', category: 'fx', keyShortcut: 'X', color: '#ff9f0a', description: 'Beach sunset white noise tension riser' },
      { id: 14, name: 'KAZANTIP VOX', category: 'vocal', keyShortcut: 'C', color: '#ffd60a', description: '"KAZANTIP / VSE BUDE DOBRE"' },
      { id: 15, name: 'FESTIVAL IMPACT', category: 'fx', keyShortcut: 'V', color: '#39FF14', description: 'Massive open-air festival sub impact' },
    ],
  },
  F: {
    id: 'F',
    name: 'DAVID GUETTA • FUTURE RAVE',
    artist: 'GUETTA & MORTEN',
    subtitle: 'Cyberpunk titanium saw plucks, modern future rave kicks, metallic percs & sub bombs',
    color: '#00F0FF',
    defaultBpm: 128,
    pads: [
      { id: 0, name: 'FUTURE RAVE KICK', category: 'kick', keyShortcut: '1', color: '#00F0FF', description: 'Punchy titanium future rave kick' },
      { id: 1, name: 'TITANIUM BASS', category: 'sub', keyShortcut: '2', color: '#ff9f0a', description: 'Sub rolling cyberpunk saw bass' },
      { id: 2, name: 'FUTURE RAVE CLAP', category: 'clap', keyShortcut: '3', color: '#5ac8fa', description: 'Crisp tight modern stadium clap' },
      { id: 3, name: 'PUNCH REVERSE', category: 'sub', keyShortcut: '4', color: '#ff375f', description: 'Tight offbeat reverse punch' },
      { id: 4, name: 'TITANIUM SAW LEAD', category: 'synth', keyShortcut: 'Q', color: '#39FF14', description: 'Signature Guetta & MORTEN saw pluck' },
      { id: 5, name: 'CYBER HAT', category: 'hihat', keyShortcut: 'W', color: '#ffd60a', description: 'Ultra-crisp modern titanium closed hat' },
      { id: 6, name: 'TITANIUM CYMBAL', category: 'hihat', keyShortcut: 'E', color: '#64d2ff', description: 'High-passed wide festival open hat' },
      { id: 7, name: 'SUB BOMB 808', category: 'sub', keyShortcut: 'R', color: '#0071e3', description: 'Deep 40Hz titanium sub drone' },
      { id: 8, name: 'FUTURE SCREECH', category: 'synth', keyShortcut: 'A', color: '#ff2d55', description: 'Cyberpunk pitch-bending synth screech' },
      { id: 9, name: 'METALLIC HIT', category: 'percussion', keyShortcut: 'S', color: '#32ade6', description: 'Sharp titanium metallic anvil impact' },
      { id: 10, name: 'DARK RAVE CHORD', category: 'synth', keyShortcut: 'D', color: '#bf5af2', description: 'Titanium detuned minor rave chord' },
      { id: 11, name: 'CYBER LASER', category: 'fx', keyShortcut: 'F', color: '#64d2ff', description: 'Fast futuristic pitch laser zapper' },
      { id: 12, name: 'DEEP SUB SLIDE', category: 'sub', keyShortcut: 'Z', color: '#5e5ce6', description: 'Pitch dive sub shockwave' },
      { id: 13, name: 'WHITE NOISE SWEEP', category: 'fx', keyShortcut: 'X', color: '#bf5af2', description: 'Future rave build-up noise' },
      { id: 14, name: 'GUETTA VOX', category: 'vocal', keyShortcut: 'C', color: '#ff9f0a', description: '"FUTURE RAVE / NEVER BE ALONE"' },
      { id: 15, name: 'TITANIUM DROP', category: 'fx', keyShortcut: 'V', color: '#00F0FF', description: 'Heavy futuristic sub drop' },
    ],
  },
  G: {
    id: 'G',
    name: 'GARD TECHNO • SCHRANZ & INDUSTRIAL',
    artist: 'HARD TECHNO / SCHRANZ',
    subtitle: '152 BPM brutal warehouse hammer kicks, metallic anvil hits, filter screeches & acid clangs',
    color: '#FF2D55',
    defaultBpm: 152,
    pads: [
      { id: 0, name: 'WAREHOUSE HAMMER', category: 'kick', keyShortcut: '1', color: '#FF2D55', description: '152 BPM overdriven Berlin hammer kick' },
      { id: 1, name: 'DISTORTED RUMBLE', category: 'sub', keyShortcut: '2', color: '#ff9f0a', description: 'Aggressive clipped industrial rumble' },
      { id: 2, name: 'INDUSTRIAL CLAP', category: 'clap', keyShortcut: '3', color: '#5ac8fa', description: 'Abrasive gated warehouse clap' },
      { id: 3, name: 'SCHRANZ PUNCH', category: 'sub', keyShortcut: '4', color: '#39FF14', description: 'Hardcore offbeat reverse punch' },
      { id: 4, name: 'ANVIL METALLIC', category: 'percussion', keyShortcut: 'Q', color: '#ffd60a', description: 'Heavy steel anvil impact hit' },
      { id: 5, name: 'HARSH CLOSED HAT', category: 'hihat', keyShortcut: 'W', color: '#ffd60a', description: 'High-velocity 16th industrial hat' },
      { id: 6, name: 'PIERCING OPEN HAT', category: 'hihat', keyShortcut: 'E', color: '#64d2ff', description: 'Ear-piercing industrial open hat' },
      { id: 7, name: 'DARK SUB DRONE', category: 'sub', keyShortcut: 'R', color: '#0071e3', description: 'Sub-bass distortion hum 38Hz' },
      { id: 8, name: 'FILTER SCREECH', category: 'synth', keyShortcut: 'A', color: '#FF2D55', description: 'Abrasive resonance filter scream' },
      { id: 9, name: 'CLANG PERCUSSION', category: 'percussion', keyShortcut: 'S', color: '#32ade6', description: 'Metallic oil drum hit' },
      { id: 10, name: 'INDUSTRIAL STAB', category: 'synth', keyShortcut: 'D', color: '#bf5af2', description: 'Harsh distorted schranz synth stab' },
      { id: 11, name: 'SCHRANZ ROLL', category: 'percussion', keyShortcut: 'F', color: '#ff375f', description: 'Relentless 16th industrial perc roll' },
      { id: 12, name: 'SUB BOMB SLAM', category: 'sub', keyShortcut: 'Z', color: '#5e5ce6', description: 'Massive clipped sub impact boom' },
      { id: 13, name: 'ABRASIVE RISER', category: 'fx', keyShortcut: 'X', color: '#FF2D55', description: 'Distorted filter sweep tension' },
      { id: 14, name: 'TECHNO SHOUT', category: 'vocal', keyShortcut: 'C', color: '#ffd60a', description: '"FASTER / HARDER TECHNO"' },
      { id: 15, name: 'METALLIC CRASH', category: 'fx', keyShortcut: 'V', color: '#FF2D55', description: 'Warehouse concrete explosion crash' },
    ],
  },
};


